language: elixir

elixir:
  - 1.4.5

otp_release:
  - 20.0

addons:
  postgresql: "9.4"

env:
  - MIX_ENV=test

before_install:
  - cp config/dev.secret.exs.example config/dev.secret.exs

cache:
  directories:
    - _build
    - deps
