---
# Install ansible on build system
#
# ansible-playbook -u $USER -v -l build-servers playbooks/setup-ansible.yml -D

- name: install ansible
  hosts: '*'
  become: true
  vars:
    tools_other_packages: "{{ ansible_build_deps }}"
    tools_other_pip:
      - paramiko
      - ansible
  vars_files:
     - ../vars/build-{{ ansible_os_family }}.yml
  roles:
    - tools-other
