---
# tasks file for app/deploy
#
# These tasks deploy the app. They are run under the deploy user account.

- name: Set vars
  set_fact:
    # Location on local filesystem of release files
    local_release_dir: "{{ role_path }}/../../../_build/{{ app_env }}/rel/{{ app_name_code }}/releases"
    # Name of target directory
    release_timestamp: "{{ ansible_date_time['iso8601_basic_short'] }}"

- block:
  - name: Get release version file
    set_fact:
      release_version_file: "{{ local_release_dir }}/start_erl.data"

  - name: Get release version data
    set_fact:
      release_version_data: "{{ lookup('file', release_version_file) }}"

  - name: Get app version
    set_fact:
      app_version: "{{ release_version_data.split(' ')[-1] }}"

  when: app_version is not defined

- name: Get local release file
  set_fact:
    local_release_file: "{{ local_release_dir }}/{{ app_version }}/{{ app_name_code }}.tar.gz"

- name: Create release dir
  file: path={{ releases_dir }}/{{ release_timestamp }} state=directory mode=0755

- block:
  - name: Upload release
    unarchive: src={{ local_release_file }} dest={{ releases_dir }}/{{ release_timestamp }}

  - name: Create current symlink
    file: src={{ releases_dir }}/{{ release_timestamp }} dest={{ deploy_dir }}/current state=link

  - name: Set permissions on release scripts
    file: path={{ item.path }} mode=0755 owner={{ deploy_user }} group={{ deploy_group }}
    with_items:
      - path: "{{ deploy_dir }}/current/bin/{{ app_name_code }}"
      - path: "{{ deploy_dir }}/current/releases/{{ app_version }}/{{ app_name_code }}.sh"

  when: not ansible_check_mode

- name: Restart app using systemctl
  command: sudo /bin/systemctl restart {{ app_name}}
  when: "app_restart_method == 'systemctl'"
  # when: "ansible_service_mgr == 'systemd' or (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7')"

- name: Touch shutdown flag file
  file:
    path: "{{ app_shutdown_flag_file }}"
    state: touch
    mode: '0660'
    owner: "{{ deploy_user }}"
    group: "{{ app_group }}"
  when: "app_restart_method == 'touch'"
