# Vars for web-servers group
postgresql_version: 10

postgresql_users:
  - name: "{{ elixir_release_name_code }}"
    pass: "{{ db_pass }}"
    encrypted: yes

postgresql_databases:
  - name: "{{ elixir_release_name_code }}_prod"
    owner: "{{ elixir_release_name_code }}"

postgresql_user_privileges:
  - name: "{{ elixir_release_name_code }}"
    db: "{{ elixir_release_name_code }}_prod"
    priv: 'ALL'
    role_attr_flags: 'LOGIN,NOSUPERUSER,NOCREATEDB'

postgresql_default_auth_method: "md5"

postgresql_pg_hba_default:
  # - { type: local, database: all, user: "{{ postgresql_admin_user }}", address: "", method: "{{ postgresql_default_auth_method }}", comment: "" }
  - { type: local, database: all, user: "{{ postgresql_admin_user }}", address: "", method: "trust", comment: "" }
  - { type: local, database: all, user: all, address: "",             method: "{{ postgresql_default_auth_method }}", comment: '"local" is for Unix domain socket connections only' }
  - { type: host,  database: all, user: all, address: "127.0.0.1/32", method: "{{ postgresql_default_auth_method }}", comment: "IPv4 local connections:" }
  - { type: host,  database: all, user: all, address: "::1/128",      method: "{{ postgresql_default_auth_method }}", comment: "IPv6 local connections:" }
